services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example123
      MYSQL_DATABASE: demos
    volumes:
      - ./data/db:/var/lib/mysql
volumes:
  db:
